### ISSUE TITLE
StarMash game blocked

### ISSUE THREAD

**Issue by THEtomaso** [LanikSJ/ubo-filters#134]
Full report here:
https://github.com/easylist/easylist/issues/4736#issuecomment-576122364

**Comment by peace2000** [comment]
It's best to report Ubo stuff here: https://github.com/uBlockOrigin/uAssets/issues

**Comment by THEtomaso** [comment]
What do you mean?
LanikSJ's filters are the ones that are causing this issue, so I'm notifying him about it here, at his own repo!

**Comment by peace2000** [comment]
So they are not general ubo filters? Ok sorry.

**Comment by LanikSJ** [comment]
I do but with all of 5 people using these lists it's not worth the effort. I'll update it next time I'm making changes to this list. Not worth the effort for one change.
