### ISSUE TITLE
🐛 [BUG] - https://floweryfact.com/

### ISSUE THREAD

**Issue by sunnywu484** [LanikSJ/ubo-filters#431]
### Description

https://floweryfact.com/
Admiral Detection Domain

Found through http://howtogeek.com/ when access via Android phone.

### AdBlocker Name

AdGuard

### Reproduction steps

```bash
1. Go to https://floweryfact.com/
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
none
```

### Logs

```bash
n/a
```

**Comment by LanikSJ** [comment]
The Admiral Domains list is pulled upstream from https://github.com/jkrejcha/AdmiraList and looks like they already have a bug for this: https://github.com/jkrejcha/AdmiraList/pull/38

I'll see if I can manually add it for time being but it might take me a few days to get to it.

**Comment by LanikSJ** [comment]
Since you're using AdGouard I would report it to them.  I don't see the domain if you could post the logger output that shows it as one of the domains I'll go ahead and add it.
