### ISSUE TITLE
🐛 [BUG] - PR #535 undid PR #531

### ISSUE THREAD

**Issue by CodeSmithian** [LanikSJ/ubo-filters#539]
### Description

On August 4, 2024 I submitted PR #531 to update Admiral domains.  I noticed later that day that github-actions merged in PR #535 which seems to have reverted PR #531.  This seems to be a mistake?

When submitting #531 I followed the instructions here: https://github.com/LanikSJ/ubo-filters/blob/main/.github/CONTRIBUTING.md

Please let me know if I incorrectly submitted #531 and I would be more than happy to correct and/or contribute differently next time.  Thanks in advance for your help!

### AdBlocker Name

uBlock Origin

### Reproduction steps

```bash
1. This is an issue in GitHub PR workflows.  Details in the description
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by LanikSJ** [comment]
> Please let me know if I incorrectly submitted #531 and I would be more than happy to correct and/or contribute differently next time. Thanks in advance for your help!

That was a GitHub Action that overwrote the code I'll debug and revert that commit.  Thank you for bring this up. 👍
