### ISSUE TITLE
oregonlive.com

### ISSUE THREAD

**Issue by smed79** [LanikSJ/ubo-filters#80]
This is a request to add `oregonlive.com` to "[admiral-domains.txt](https://github.com/LanikSJ/ubo-filters/blob/master/filters/admiral-domains.txt)" 

Section ==> `! RegEx Filter`

replace 
`...|oportaln10.com.br|paidikestainies.online|...` 
by 
`...|oportaln10.com.br|oregonlive.com|paidikestainies.online|...`

source: _https://forums.lanik.us/viewtopic.php?f=62&t=43185_

--
PS: _Please keep this issue open for future submissions_.

**Comment by LanikSJ** [comment]
Let's stick to one domain per Issue.  Makes it easier to search through the issue reports.

**Comment by smed79** [comment]
Ok, thank you.
